--Employee that made the highest revenue
WITH customer_revenue AS
(SELECT customerid, COUNT(DISTINCT(customerid)) AS customer_count, SUM (total) AS revenue_total
FROM invoice
GROUP BY customerid)

SELECT SUM (cr.revenue_total) AS total_rev, cr.customer_count, em.employeeid,em.firstname || ''|| em.lastname AS employee_name
FROM customer_revenue cr
JOIN customer c ON cr.customerid = c.customerid
JOIN employee em ON c.supportrepid = em.employeeid
GROUP BY em.employeeid,employee_name, cr.customer_count
ORDER BY total_rev DESC;

--Revenue generated by employee by customer
WITH customer_revenue AS
(SELECT customerid, SUM (total) AS revenue_total
FROM invoice
GROUP BY customerid)

SELECT SUM (cr.revenue_total) AS total_rev, em.employeeid,em.firstname || ''|| em.lastname AS employee_name
FROM customer_revenue cr
JOIN customer c ON cr.customerid = c.customerid
JOIN employee em ON c.supportrepid = em.employeeid
GROUP BY em.employeeid,employee_name 
ORDER BY total_rev DESC;



--Revenue by country
WITH customer_revenue AS
(SELECT customerid, SUM (total) AS revenue_total
FROM invoice
GROUP BY customerid)

SELECT c.country,SUM (cr.revenue_total) AS total_rev
FROM customer_revenue cr
JOIN customer c ON cr.customerid = c.customerid
GROUP BY c.country
ORDER BY total_rev DESC;


--Customer frequency and their country
WITH customer_revenue AS
(SELECT customerid, SUM (total) AS revenue_total, COUNT (invoiceid) AS customer_freq
FROM invoice
GROUP BY customerid)

SELECT cr.customerid,c.firstname || ''||lastname AS customer_name, cr.revenue_total, c.country, cr.customer_freq
FROM customer_revenue cr
JOIN customer c ON cr.customerid = c.customerid
GROUP BY cr.customerid, cr.revenue_total, c.country, cr.customer_freq, customer_name
ORDER BY cr.revenue_total DESC;



--Employee revenue generation by customers
CREATE VIEW vw_employee_rev AS
	WITH customer_revenue AS
	(SELECT customerid, SUM (total) AS revenue_total, COUNT (invoiceid) AS customer_freq
	FROM invoice
	GROUP BY customerid)
	
	SELECT cr.customerid, em.employeeid,em.firstname || ''|| em.lastname AS employee_name,cr.revenue_total
	FROM customer_revenue cr
	JOIN customer c ON cr.customerid = c.customerid
	JOIN employee em ON c.supportrepid = em.employeeid
	GROUP BY cr.customerid, cr.revenue_total,em.employeeid,employee_name 
	ORDER BY em.employeeid DESC;